service:
  name: aws-lambda-ts
app: education
tenant: himkwtn
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1

functions:
  - hello:
      handler: handler.hello
      events:
        - http:
            method: get
            path: hello
  - ${file(./src/animals/animals.functions.yml)}
