service:
  name: aws-lambda-ts
app: education
tenant: himkwtn
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource: ${env:DYNAMO_ARN}

functions:
  - hello:
      handler: handler.hello
      events:
        - http:
            method: get
            path: hello
  - ${file(./src/animals/animals.functions.yml)}
